import type { Ipo, ScorecardRow, MarketMeter } from "../types"

// Representative sample data used ONLY as a fallback when the FastAPI
// backend is unreachable (for example inside the v0 preview, where the
// Python server is not running). No business logic is hardcoded here —
// these are illustrative rows so the full premium UI is visible.

export const SAMPLE_IPOS: Ipo[] = [
  {
    ipo_name: "Vertex Semiconductors Ltd",
    predicted_probability: 0.87,
    gmp_pct: 32.4,
    gmp: 78,
    decision_label: "INVEST",
    listing_date: "2026-06-20",
    open_date: "2026-06-14",
    close_date: "2026-06-18",
    subscription_x: 42.6,
    ipo_price: 241,
    lot_size: 61,
    ipo_size_cr: 420,
    has_anchor: 1,
    ipo_type: "Mainboard",
    status: "active",
  },
  {
    ipo_name: "Saffron Logistics Ltd",
    predicted_probability: 0.74,
    gmp_pct: 18.2,
    gmp: 34,
    decision_label: "INVEST",
    listing_date: "2026-06-21",
    open_date: "2026-06-15",
    close_date: "2026-06-19",
    subscription_x: 8.1,
    ipo_price: 187,
    lot_size: 80,
    ipo_size_cr: 760,
    has_anchor: 1,
    ipo_type: "Mainboard",
    status: "active",
  },
  {
    ipo_name: "Himalaya Agro Foods Ltd",
    predicted_probability: 0.31,
    gmp_pct: 2.1,
    gmp: 4,
    decision_label: "SKIP",
    listing_date: "2026-06-23",
    open_date: "2026-06-16",
    close_date: "2026-06-20",
    subscription_x: 0.8,
    ipo_price: 92,
    lot_size: 150,
    ipo_size_cr: 1850,
    has_anchor: 0,
    ipo_type: "Mainboard",
    status: "active",
  },
  {
    ipo_name: "Nimbus Cloud Tech Ltd",
    predicted_probability: 0.69,
    gmp_pct: 24.5,
    gmp: 41,
    decision_label: "INVEST",
    listing_date: "2026-06-24",
    open_date: "2026-06-17",
    close_date: "2026-06-21",
    subscription_x: 15.3,
    ipo_price: 168,
    lot_size: 88,
    ipo_size_cr: 145,
    has_anchor: 1,
    ipo_type: "SME",
    status: "active",
  },
  {
    ipo_name: "Coastal Marine Exports Ltd",
    predicted_probability: 0.22,
    gmp_pct: -1.5,
    gmp: -3,
    decision_label: "SKIP",
    listing_date: "2026-06-25",
    open_date: "2026-06-18",
    close_date: "2026-06-22",
    subscription_x: 0.6,
    ipo_price: 205,
    lot_size: 600,
    ipo_size_cr: 62,
    has_anchor: 0,
    ipo_type: "SME",
    status: "active",
  },
  {
    ipo_name: "Aurora Renewables Ltd",
    predicted_probability: 0.81,
    gmp_pct: 28.0,
    gmp: 56,
    decision_label: "INVEST",
    listing_date: "2026-06-13",
    open_date: "2026-06-09",
    close_date: "2026-06-11",
    subscription_x: 36.2,
    ipo_price: 200,
    lot_size: 75,
    ipo_size_cr: 510,
    has_anchor: 1,
    ipo_type: "Mainboard",
    status: "closed",
  },
]

export const SAMPLE_SCORECARD: ScorecardRow[] = [
  {
    ipo_name: "Quantum Defence Systems Ltd",
    decision_label: "INVEST",
    gmp_pct: 41.0,
    actual_gain_pct: 38.4,
    was_correct: 1,
    model_accuracy: 78.5,
  },
  {
    ipo_name: "Greenfield Pharma Ltd",
    decision_label: "INVEST",
    gmp_pct: 22.0,
    actual_gain_pct: 27.1,
    was_correct: 1,
    model_accuracy: 78.5,
  },
  {
    ipo_name: "Metro Infra Projects Ltd",
    decision_label: "SKIP",
    gmp_pct: 3.0,
    actual_gain_pct: -6.2,
    was_correct: 1,
    model_accuracy: 78.5,
  },
  {
    ipo_name: "Sunrise Textiles Ltd",
    decision_label: "INVEST",
    gmp_pct: 12.0,
    actual_gain_pct: -2.4,
    was_correct: 0,
    model_accuracy: 78.5,
  },
]

export const SAMPLE_MARKET_METER: MarketMeter = {
  score: 64,
  mood_label: "Greed",
  color: "#10b981",
  nifty_price: 24812.35,
  nifty_change_pct: 0.64,
  vix_value: 13.42,
  updated_at: "2026-06-14T10:30:00",
}
